spring:
  application:
    name: "assignment-cfg-example"
    setApiMessage: "thanks for using my api"
  datasource:
    url: jdbc:mysql://localhost:3306/animals
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    the above will be red until you've added in the dependencies mentioned
    username: root
    password: password #your password